--------------------------------------------------------
--  File created - Saturday-May-24-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence SEQ_ADMIN_TAB
--------------------------------------------------------

   CREATE SEQUENCE  "HAMHAMA"."SEQ_ADMIN_TAB"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CLIENT
--------------------------------------------------------

   CREATE SEQUENCE  "HAMHAMA"."SEQ_CLIENT"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CLIENTFEEDBACK
--------------------------------------------------------

   CREATE SEQUENCE  "HAMHAMA"."SEQ_CLIENTFEEDBACK"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_FEEDBACK
--------------------------------------------------------

   CREATE SEQUENCE  "HAMHAMA"."SEQ_FEEDBACK"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 61 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_MENUITEM
--------------------------------------------------------

   CREATE SEQUENCE  "HAMHAMA"."SEQ_MENUITEM"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_RESERVATION
--------------------------------------------------------

   CREATE SEQUENCE  "HAMHAMA"."SEQ_RESERVATION"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_RESTAURANTTABLE
--------------------------------------------------------

   CREATE SEQUENCE  "HAMHAMA"."SEQ_RESTAURANTTABLE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_TABLE
--------------------------------------------------------

   CREATE SEQUENCE  "HAMHAMA"."SEQ_TABLE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_USER
--------------------------------------------------------

   CREATE SEQUENCE  "HAMHAMA"."SEQ_USER"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 61 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_USR
--------------------------------------------------------

   CREATE SEQUENCE  "HAMHAMA"."SEQ_USR"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table ADMIN_TAB
--------------------------------------------------------

  CREATE TABLE "HAMHAMA"."ADMIN_TAB" 
   (	"ADMIN_ID" NUMBER(*,0), 
	"USERNAME" VARCHAR2(100 BYTE), 
	"PWD" VARCHAR2(100 BYTE), 
	"TIME_CREATED" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CLIENT
--------------------------------------------------------

  CREATE TABLE "HAMHAMA"."CLIENT" 
   (	"CLIENT_ID" NUMBER(*,0), 
	"FULL_NAME" VARCHAR2(100 BYTE), 
	"NUM_PHONE" VARCHAR2(20 BYTE), 
	"EMAIL" VARCHAR2(100 BYTE), 
	"TIME_CREATED" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CLIENTFEEDBACK
--------------------------------------------------------

  CREATE TABLE "HAMHAMA"."CLIENTFEEDBACK" 
   (	"FEEDBACK_ID" NUMBER(*,0), 
	"ITEM_ID" NUMBER(*,0), 
	"RATING" NUMBER(*,0), 
	"COMNT" VARCHAR2(1000 BYTE), 
	"DATE_INTERACTED" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MENUITEM
--------------------------------------------------------

  CREATE TABLE "HAMHAMA"."MENUITEM" 
   (	"ITEM_ID" NUMBER, 
	"NAME_ITEM" VARCHAR2(100 BYTE), 
	"DISPONIBLE" NUMBER(1,0) DEFAULT 1, 
	"DESCRIPTION" VARCHAR2(1000 BYTE), 
	"IMAGEPATH" VARCHAR2(1000 BYTE), 
	"PRIX" NUMBER(10,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table RESERVATION
--------------------------------------------------------

  CREATE TABLE "HAMHAMA"."RESERVATION" 
   (	"RESERVATION_ID" NUMBER, 
	"RESERVATION_DATETIME" TIMESTAMP (6), 
	"NBR_PERSONNES" NUMBER, 
	"CHOIX_ITEM" VARCHAR2(255 BYTE), 
	"TIME_CREATED" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	"CLIENT_ID" NUMBER(*,0), 
	"TABLE_ID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table RESTAURANTTABLE
--------------------------------------------------------

  CREATE TABLE "HAMHAMA"."RESTAURANTTABLE" 
   (	"TABLE_ID" NUMBER, 
	"NUM_TABLE" NUMBER, 
	"SEATS" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USR
--------------------------------------------------------

  CREATE TABLE "HAMHAMA"."USR" 
   (	"USER_ID" NUMBER(*,0), 
	"FULL_NAME" VARCHAR2(255 BYTE), 
	"EMAIL" VARCHAR2(255 BYTE), 
	"TIME_CREATED" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into HAMHAMA.ADMIN_TAB
SET DEFINE OFF;
Insert into HAMHAMA.ADMIN_TAB (ADMIN_ID,USERNAME,PWD,TIME_CREATED) values (1,'souhail','1234',to_timestamp('24-MAY-25 08.26.11.828000000 PM','DD-MON-RR HH.MI.SS.FF AM'));
Insert into HAMHAMA.ADMIN_TAB (ADMIN_ID,USERNAME,PWD,TIME_CREATED) values (2,'mahdi','1234',to_timestamp('24-MAY-25 08.26.11.828000000 PM','DD-MON-RR HH.MI.SS.FF AM'));
Insert into HAMHAMA.ADMIN_TAB (ADMIN_ID,USERNAME,PWD,TIME_CREATED) values (3,'ghaith','1234',to_timestamp('24-MAY-25 08.26.11.829000000 PM','DD-MON-RR HH.MI.SS.FF AM'));
REM INSERTING into HAMHAMA.CLIENT
SET DEFINE OFF;
Insert into HAMHAMA.CLIENT (CLIENT_ID,FULL_NAME,NUM_PHONE,EMAIL,TIME_CREATED) values (4,'Youssef Daghfous','21698765432','youssef.daghfous@example.com',to_timestamp('24-MAY-25 08.26.11.829000000 PM','DD-MON-RR HH.MI.SS.FF AM'));
Insert into HAMHAMA.CLIENT (CLIENT_ID,FULL_NAME,NUM_PHONE,EMAIL,TIME_CREATED) values (5,'Sarra Mahfoudh','21699887766','sarra.mahfoudh@example.com',to_timestamp('24-MAY-25 08.26.11.830000000 PM','DD-MON-RR HH.MI.SS.FF AM'));
Insert into HAMHAMA.CLIENT (CLIENT_ID,FULL_NAME,NUM_PHONE,EMAIL,TIME_CREATED) values (6,'Omar Jaziri','21691234567','omar.jaziri@example.com',to_timestamp('24-MAY-25 08.26.11.830000000 PM','DD-MON-RR HH.MI.SS.FF AM'));
REM INSERTING into HAMHAMA.CLIENTFEEDBACK
SET DEFINE OFF;
Insert into HAMHAMA.CLIENTFEEDBACK (FEEDBACK_ID,ITEM_ID,RATING,COMNT,DATE_INTERACTED) values (43,1,5,'Couscous d�licieux !',to_timestamp('24-MAY-25 08.26.11.833000000 PM','DD-MON-RR HH.MI.SS.FF AM'));
Insert into HAMHAMA.CLIENTFEEDBACK (FEEDBACK_ID,ITEM_ID,RATING,COMNT,DATE_INTERACTED) values (44,2,4,'Brik croustillant et bien garni.',to_timestamp('24-MAY-25 08.26.11.833000000 PM','DD-MON-RR HH.MI.SS.FF AM'));
REM INSERTING into HAMHAMA.MENUITEM
SET DEFINE OFF;
Insert into HAMHAMA.MENUITEM (ITEM_ID,NAME_ITEM,DISPONIBLE,DESCRIPTION,IMAGEPATH,PRIX) values (1,'Couscous au Poulet',1,'Semoule cuite � la vapeur avec l�gumes et poulet �pic�','/images/couscous.jpg',18.5);
Insert into HAMHAMA.MENUITEM (ITEM_ID,NAME_ITEM,DISPONIBLE,DESCRIPTION,IMAGEPATH,PRIX) values (2,'Brik � l''�uf',1,'Feuille de malsouka farcie avec �uf, thon et c�pres','/images/brik.jpg',6.5);
Insert into HAMHAMA.MENUITEM (ITEM_ID,NAME_ITEM,DISPONIBLE,DESCRIPTION,IMAGEPATH,PRIX) values (3,'Ojja Merguez',1,'�ufs poch�s dans une sauce tomate �pic�e avec merguez','/images/ojja.jpg',12);
REM INSERTING into HAMHAMA.RESERVATION
SET DEFINE OFF;
Insert into HAMHAMA.RESERVATION (RESERVATION_ID,RESERVATION_DATETIME,NBR_PERSONNES,CHOIX_ITEM,TIME_CREATED,CLIENT_ID,TABLE_ID) values (1,to_timestamp('25-MAY-25 01.00.00.000000000 PM','DD-MON-RR HH.MI.SS.FF AM'),2,'Couscous au Poulet, Brik � l''�uf',to_timestamp('24-MAY-25 08.26.11.832000000 PM','DD-MON-RR HH.MI.SS.FF AM'),4,25);
Insert into HAMHAMA.RESERVATION (RESERVATION_ID,RESERVATION_DATETIME,NBR_PERSONNES,CHOIX_ITEM,TIME_CREATED,CLIENT_ID,TABLE_ID) values (2,to_timestamp('25-MAY-25 08.00.00.000000000 PM','DD-MON-RR HH.MI.SS.FF AM'),3,'Ojja Merguez',to_timestamp('24-MAY-25 08.26.11.833000000 PM','DD-MON-RR HH.MI.SS.FF AM'),5,26);
REM INSERTING into HAMHAMA.RESTAURANTTABLE
SET DEFINE OFF;
Insert into HAMHAMA.RESTAURANTTABLE (TABLE_ID,NUM_TABLE,SEATS) values (25,1,4);
Insert into HAMHAMA.RESTAURANTTABLE (TABLE_ID,NUM_TABLE,SEATS) values (26,2,6);
REM INSERTING into HAMHAMA.USR
SET DEFINE OFF;
Insert into HAMHAMA.USR (USER_ID,FULL_NAME,EMAIL,TIME_CREATED) values (1,'Souhail Akermi','souhail.admin@hamhamma.tn',to_date('24-MAY-25','DD-MON-RR'));
Insert into HAMHAMA.USR (USER_ID,FULL_NAME,EMAIL,TIME_CREATED) values (2,'Mahdi Chaabani','mahdi.admin@hamhamma.tn',to_date('24-MAY-25','DD-MON-RR'));
Insert into HAMHAMA.USR (USER_ID,FULL_NAME,EMAIL,TIME_CREATED) values (3,'Ghaith Homrani','ghaith.admin@hamhamma.tn',to_date('24-MAY-25','DD-MON-RR'));
Insert into HAMHAMA.USR (USER_ID,FULL_NAME,EMAIL,TIME_CREATED) values (4,'Youssef Daghfous','youssef.daghfous@example.com',to_date('24-MAY-25','DD-MON-RR'));
Insert into HAMHAMA.USR (USER_ID,FULL_NAME,EMAIL,TIME_CREATED) values (5,'Sarra Mahfoudh','sarra.mahfoudh@example.com',to_date('24-MAY-25','DD-MON-RR'));
Insert into HAMHAMA.USR (USER_ID,FULL_NAME,EMAIL,TIME_CREATED) values (6,'Omar Jaziri','omar.jaziri@example.com',to_date('24-MAY-25','DD-MON-RR'));
--------------------------------------------------------
--  DDL for Index PK_MENUITEM
--------------------------------------------------------

  CREATE UNIQUE INDEX "HAMHAMA"."PK_MENUITEM" ON "HAMHAMA"."MENUITEM" ("ITEM_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_RESTAURANTTABLE
--------------------------------------------------------

  CREATE UNIQUE INDEX "HAMHAMA"."PK_RESTAURANTTABLE" ON "HAMHAMA"."RESTAURANTTABLE" ("TABLE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_USR
--------------------------------------------------------

  CREATE UNIQUE INDEX "HAMHAMA"."PK_USR" ON "HAMHAMA"."USR" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_CLIENT
--------------------------------------------------------

  CREATE UNIQUE INDEX "HAMHAMA"."PK_CLIENT" ON "HAMHAMA"."CLIENT" ("CLIENT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_ADMIN_TAB
--------------------------------------------------------

  CREATE UNIQUE INDEX "HAMHAMA"."PK_ADMIN_TAB" ON "HAMHAMA"."ADMIN_TAB" ("ADMIN_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_RESERVATION
--------------------------------------------------------

  CREATE UNIQUE INDEX "HAMHAMA"."PK_RESERVATION" ON "HAMHAMA"."RESERVATION" ("RESERVATION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_CLIENTFEEDBACK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HAMHAMA"."PK_CLIENTFEEDBACK" ON "HAMHAMA"."CLIENTFEEDBACK" ("FEEDBACK_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table USR
--------------------------------------------------------

  ALTER TABLE "HAMHAMA"."USR" ADD CONSTRAINT "PK_USR" PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HAMHAMA"."USR" MODIFY ("TIME_CREATED" NOT NULL ENABLE);
  ALTER TABLE "HAMHAMA"."USR" MODIFY ("FULL_NAME" NOT NULL ENABLE);
  ALTER TABLE "HAMHAMA"."USR" MODIFY ("USER_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RESERVATION
--------------------------------------------------------

  ALTER TABLE "HAMHAMA"."RESERVATION" ADD CONSTRAINT "PK_RESERVATION" PRIMARY KEY ("RESERVATION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HAMHAMA"."RESERVATION" MODIFY ("NBR_PERSONNES" NOT NULL ENABLE);
  ALTER TABLE "HAMHAMA"."RESERVATION" MODIFY ("RESERVATION_DATETIME" NOT NULL ENABLE);
  ALTER TABLE "HAMHAMA"."RESERVATION" MODIFY ("RESERVATION_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CLIENTFEEDBACK
--------------------------------------------------------

  ALTER TABLE "HAMHAMA"."CLIENTFEEDBACK" ADD CONSTRAINT "PK_CLIENTFEEDBACK" PRIMARY KEY ("FEEDBACK_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HAMHAMA"."CLIENTFEEDBACK" ADD CONSTRAINT "CHK_RATING" CHECK (RATING BETWEEN 1 AND 5) ENABLE;
  ALTER TABLE "HAMHAMA"."CLIENTFEEDBACK" MODIFY ("ITEM_ID" NOT NULL ENABLE);
  ALTER TABLE "HAMHAMA"."CLIENTFEEDBACK" MODIFY ("FEEDBACK_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RESTAURANTTABLE
--------------------------------------------------------

  ALTER TABLE "HAMHAMA"."RESTAURANTTABLE" ADD CONSTRAINT "PK_RESTAURANTTABLE" PRIMARY KEY ("TABLE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HAMHAMA"."RESTAURANTTABLE" ADD CONSTRAINT "CHK_SEATS" CHECK (SEATS BETWEEN 1 AND 10) ENABLE;
  ALTER TABLE "HAMHAMA"."RESTAURANTTABLE" MODIFY ("SEATS" NOT NULL ENABLE);
  ALTER TABLE "HAMHAMA"."RESTAURANTTABLE" MODIFY ("NUM_TABLE" NOT NULL ENABLE);
  ALTER TABLE "HAMHAMA"."RESTAURANTTABLE" MODIFY ("TABLE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ADMIN_TAB
--------------------------------------------------------

  ALTER TABLE "HAMHAMA"."ADMIN_TAB" ADD CONSTRAINT "PK_ADMIN_TAB" PRIMARY KEY ("ADMIN_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HAMHAMA"."ADMIN_TAB" MODIFY ("PWD" NOT NULL ENABLE);
  ALTER TABLE "HAMHAMA"."ADMIN_TAB" MODIFY ("USERNAME" NOT NULL ENABLE);
  ALTER TABLE "HAMHAMA"."ADMIN_TAB" MODIFY ("ADMIN_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CLIENT
--------------------------------------------------------

  ALTER TABLE "HAMHAMA"."CLIENT" ADD CONSTRAINT "PK_CLIENT" PRIMARY KEY ("CLIENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HAMHAMA"."CLIENT" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "HAMHAMA"."CLIENT" MODIFY ("NUM_PHONE" NOT NULL ENABLE);
  ALTER TABLE "HAMHAMA"."CLIENT" MODIFY ("FULL_NAME" NOT NULL ENABLE);
  ALTER TABLE "HAMHAMA"."CLIENT" MODIFY ("CLIENT_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MENUITEM
--------------------------------------------------------

  ALTER TABLE "HAMHAMA"."MENUITEM" ADD CONSTRAINT "PK_MENUITEM" PRIMARY KEY ("ITEM_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HAMHAMA"."MENUITEM" ADD CONSTRAINT "CHK_DISPONIBLE" CHECK (DISPONIBLE IN (0, 1)) ENABLE;
  ALTER TABLE "HAMHAMA"."MENUITEM" MODIFY ("PRIX" NOT NULL ENABLE);
  ALTER TABLE "HAMHAMA"."MENUITEM" MODIFY ("NAME_ITEM" NOT NULL ENABLE);
  ALTER TABLE "HAMHAMA"."MENUITEM" MODIFY ("ITEM_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table ADMIN_TAB
--------------------------------------------------------

  ALTER TABLE "HAMHAMA"."ADMIN_TAB" ADD CONSTRAINT "FK_ADMIN_USR" FOREIGN KEY ("ADMIN_ID")
	  REFERENCES "HAMHAMA"."USR" ("USER_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CLIENT
--------------------------------------------------------

  ALTER TABLE "HAMHAMA"."CLIENT" ADD CONSTRAINT "FK_CLIENT_USR" FOREIGN KEY ("CLIENT_ID")
	  REFERENCES "HAMHAMA"."USR" ("USER_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CLIENTFEEDBACK
--------------------------------------------------------

  ALTER TABLE "HAMHAMA"."CLIENTFEEDBACK" ADD CONSTRAINT "FK_CLIENTFEED_ITEM" FOREIGN KEY ("ITEM_ID")
	  REFERENCES "HAMHAMA"."MENUITEM" ("ITEM_ID") ENABLE;

--------------------------------------------------------
--  Ref Constraints for Table RESERVATION
--------------------------------------------------------

  ALTER TABLE "HAMHAMA"."RESERVATION" ADD CONSTRAINT "FK_RESERVATION_CLIENT" FOREIGN KEY ("CLIENT_ID")
	  REFERENCES "HAMHAMA"."CLIENT" ("CLIENT_ID") ENABLE;
  ALTER TABLE "HAMHAMA"."RESERVATION" ADD CONSTRAINT "FK_RESERVATION_TABLE" FOREIGN KEY ("TABLE_ID")
	  REFERENCES "HAMHAMA"."RESTAURANTTABLE" ("TABLE_ID") ENABLE;


